image: Visual Studio 2019

install:
  # Install OpenCL headers and libraries
  - set NUGETDIR=C:\NUGET
  - nuget install opencl-nug -Version 0.777.77 -OutputDirectory %NUGETDIR%
  - dir %NUGETDIR%\opencl-nug.0.777.77\build\native\
  - set OCL_ROOT=%NUGETDIR%\opencl-nug.0.777.77\build\native
  # Install OpenCL Runtime
  - choco install opencl-intel-cpu-runtime
  # Check if it's working
  - ps: appveyor DownloadFile "https://ci.appveyor.com/api/projects/oblomov/clinfo/artifacts/clinfo.exe?job=platform:+x64" -FileName clinfo.exe
  - .\clinfo.exe

before_build:
  - cmd: dotnet --version
  - cmd: dotnet tool restore
  - cmd: dotnet paket restore

build_script:
  - cmd: dotnet build

test_script:
  - cmd: dotnet test